config/routes.rb
Rails.application.routes.draw do
  root 'meetings#index'

  resources :meetings, only: %i(index new create show)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
# Class for a group meeting
# @attr Name [String] Name of the meeting being made.
# @attr Length [Integer] How long the meeting is, in intervals of 15 min.
# @attr Leader [String] The leader of the group.
class Meeting < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :length, presence: true, numericality: { greater_than: 0 }
  validates :leader, length: { maximum: 25 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i(show)

  def index
    @meetings = Meeting.all.order('created_at DESC')
  end

  def new
    @meeting = Meeting.new
  end

  def create
    @meeting = Meeting.new(meeting_params)

    if @meeting.save
      redirect_to meeting_path(@meeting), 
        notice: 'Meeting was successfully created.'
    else
      render 'new'
    end
  end

  def show; end

  private
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    def meeting_params
      params.require(:meeting).permit(:title, :length, :leader)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupScheduler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_with(model: @meeting, local: true) do |form| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :meeting_title %>
  </div>

  <div class="field">
    <%= form.label :length %>
    <%= form.text_field :length, id: :meeting_length %>
  </div>

  <div class="field">
    <%= form.label :leader %>
    <%= form.text_field :leader, id: :meeting_leader %>
  </div>

  <div class="actions">
    <%= form.submit :class => "button" %>
  </div>
<% end %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<div>
  <h1>Meetings</h1>
  <%= button_to 'Create New Meeting', new_meeting_path, method: :get %>
</div>

<div>
  <% if @meetings.any? %>
    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Length</th>
          <th>Leader</th>
          <th>Created At</th>
        </tr>
      </thead>

      <tbody>
        <% @meetings.each do |meeting| %>
          <tr id=<%= meeting.id %>>
            <td><%= link_to meeting.title, meeting %></td>
            <td><%= meeting.length %></td>
            <td><%= meeting.leader %></td>
            <td><%= meeting.created_at.strftime("%B %d, %Y; %l:%M%p") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h2>No meetings!</h2>
  <% end %>
</div>

app/views/meetings/new.html.erb
<div>
  <h1>Create Meeting</h1>
</div>
<div>
  <%= render 'form' %>
</div>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @meeting.title %>
</p>

<p>
  <strong>Meeting Length:</strong>
  <%= @meeting.length %>
</p>

<p>
  <strong>Leader:</strong>
  <%= @meeting.leader %>
</p>